service: auction-sls-api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: dev # ${opt:stage, 'dev'}
  profile: gabesls
  region: 'us-east-1'
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements: # THIS IS IAM ACCESS CONFIG
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM} # :AuctionsTableIAM obj imported form file

resources:
  Resources: # AWS ARN SETTINGS FOR DYNAMODB, ETC
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable} # :AuctionsTable obj imported form file

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  AuctionsTable:
    name: !Ref AuctionsTable # gets the DynamoDB name
    arn: !GetAtt AuctionsTable.Arn # gets the ARN for the DynamoDb table resource
  bundle:
    linting: false
